EtcdConnectString: 127.0.0.1:2379
EtcdNameSpace: YaIce_Service
PortStart: 10001
PortEnd: 10100
HttpPort: 8888
ClusterName: YaIce
IntranetHost: 10.0.0.10
ExtranetHost: 10.0.0.10
IntranetPingService: 2000
ExtranetPingService: 5000
MaxConnectNumber: 5000
ExcelFilePath: excelconfig
LogFilePath: log/